# echo -n naveen | base64 --> bmF2ZWVu
# echo -n naveen123 | base64 --> bmF2ZWVuMTIz
# echo -n bmF2ZWVuMTIz | base64 --decode
# but we dont don't use these type of secrets in realtime
# kubectl apply -f 13secrets.yaml
# kubectl describe secret mysecret
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: bmF2ZWVu
  password: bmF2ZWVuMTIz