# kubectl apply -f 14pod_secret.yaml
# kubectl exec -it secret-pod -- bash
# env // we can see secrets here
# exit
# kubectl delete -f 14pod_secret.yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password