# kubectl apply -f 16service_node.yaml
# kubectl delete -f 16service_node.yaml
# kubectl get svc -o wide // we find port
# kubectl get pods -o wide // we find private ip
# on sg -- allow 32696 anywhere
# http://13.233.137.6:32696/ --> Node1 public IP
# http://3.110.205.54:32696/ --> Node2 Public IP
# From both nodes we can access website because Nodeport 
# user → NODE1:<NODE-PORT> → cluster IP → pod
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    server: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80