# kubectl apply -f 17service_load.yaml
# kubectl delete -f 17service_load.yaml
# No need to open port
# kubectl get svc -o wide // we find port & DNS
# ab83c0f1452f745c08b3c2a49dc5141b-1720527669.ap-south-1.elb.amazonaws.com
# kubectl get pods -o wide // we find private ip
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    server: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80