# resources limitation
# enter into container
# kubectl exec -it stress -- bash 
# stress-ng --cpu 1
# kubectl get pods -o wide // get node that it is running container
# login into ec2
# top // observe utilization of cpu (it won't go beyond 20%)
apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - image: naveen2809/stress:v1
    imagePullPolicy: Always
    name: stress
    command: ["sleep", "200"]
    resources:
      requests:
        cpu: "150m" # 1 CPU = 1000m (milli)
        memory: "200Mi" # mi = mb
      limits:
        cpu: "200m"
        memory: "300Mi"